

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BookingTab(object):
    def setupUi(self, BookingTab):
        BookingTab.setObjectName("BookingTab")
        BookingTab.resize(1160, 740)
        self.verticalLayout = QtWidgets.QVBoxLayout(BookingTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=BookingTab)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.customerCombo = QtWidgets.QComboBox(parent=self.groupBox)
        self.customerCombo.setObjectName("customerCombo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.customerCombo)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.screeningCombo = QtWidgets.QComboBox(parent=self.groupBox)
        self.screeningCombo.setObjectName("screeningCombo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.screeningCombo)
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.bookingDateInput = QtWidgets.QDateTimeEdit(parent=self.groupBox)
        self.bookingDateInput.setObjectName("bookingDateInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.bookingDateInput)
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.totalAmountInput = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.totalAmountInput.setMaximum(1000.0)
        self.totalAmountInput.setObjectName("totalAmountInput")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.totalAmountInput)
        self.verticalLayout.addWidget(self.groupBox)
        self.bookingTable = QtWidgets.QTableWidget(parent=BookingTab)
        self.bookingTable.setAlternatingRowColors(True)
        self.bookingTable.setObjectName("bookingTable")
        self.bookingTable.setColumnCount(6)
        self.bookingTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.bookingTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookingTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookingTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookingTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookingTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookingTable.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.bookingTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addBookingBtn = QtWidgets.QPushButton(parent=BookingTab)
        self.addBookingBtn.setObjectName("addBookingBtn")
        self.horizontalLayout.addWidget(self.addBookingBtn)
        self.updateBookingBtn = QtWidgets.QPushButton(parent=BookingTab)
        self.updateBookingBtn.setObjectName("updateBookingBtn")
        self.horizontalLayout.addWidget(self.updateBookingBtn)
        self.deleteBookingBtn = QtWidgets.QPushButton(parent=BookingTab)
        self.deleteBookingBtn.setObjectName("deleteBookingBtn")
        self.horizontalLayout.addWidget(self.deleteBookingBtn)
        self.refreshBookingBtn = QtWidgets.QPushButton(parent=BookingTab)
        self.refreshBookingBtn.setObjectName("refreshBookingBtn")
        self.horizontalLayout.addWidget(self.refreshBookingBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(BookingTab)
        QtCore.QMetaObject.connectSlotsByName(BookingTab)

    def retranslateUi(self, BookingTab):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox.setTitle(_translate("BookingTab", "Booking Information"))
        self.label.setText(_translate("BookingTab", "Customer:"))
        self.label_2.setText(_translate("BookingTab", "Screening:"))
        self.label_3.setText(_translate("BookingTab", "Booking Date:"))
        self.label_4.setText(_translate("BookingTab", "Total Amount:"))
        self.totalAmountInput.setPrefix(_translate("BookingTab", "$ "))
        item = self.bookingTable.horizontalHeaderItem(0)
        item.setText(_translate("BookingTab", "Booking ID"))
        item = self.bookingTable.horizontalHeaderItem(1)
        item.setText(_translate("BookingTab", "Customer"))
        item = self.bookingTable.horizontalHeaderItem(2)
        item.setText(_translate("BookingTab", "Movie"))
        item = self.bookingTable.horizontalHeaderItem(3)
        item.setText(_translate("BookingTab", "Screening Time"))
        item = self.bookingTable.horizontalHeaderItem(4)
        item.setText(_translate("BookingTab", "Booking Date"))
        item = self.bookingTable.horizontalHeaderItem(5)
        item.setText(_translate("BookingTab", "Total Amount"))
        self.addBookingBtn.setText(_translate("BookingTab", "Add Booking"))
        self.updateBookingBtn.setText(_translate("BookingTab", "Update Booking"))
        self.deleteBookingBtn.setText(_translate("BookingTab", "Delete Booking"))
        self.refreshBookingBtn.setText(_translate("BookingTab", "Refresh"))
