

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CustomerTab(object):
    def setupUi(self, CustomerTab):
        CustomerTab.setObjectName("CustomerTab")
        CustomerTab.resize(1160, 740)
        self.verticalLayout = QtWidgets.QVBoxLayout(CustomerTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=CustomerTab)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.firstNameInput = QtWidgets.QLineEdit(parent=self.groupBox)
        self.firstNameInput.setObjectName("firstNameInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.firstNameInput)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.lastNameInput = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lastNameInput.setObjectName("lastNameInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lastNameInput)
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.emailInput = QtWidgets.QLineEdit(parent=self.groupBox)
        self.emailInput.setObjectName("emailInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.emailInput)
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.phoneInput = QtWidgets.QLineEdit(parent=self.groupBox)
        self.phoneInput.setObjectName("phoneInput")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.phoneInput)
        self.verticalLayout.addWidget(self.groupBox)
        self.customerTable = QtWidgets.QTableWidget(parent=CustomerTab)
        self.customerTable.setAlternatingRowColors(True)
        self.customerTable.setObjectName("customerTable")
        self.customerTable.setColumnCount(5)
        self.customerTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.customerTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addCustomerBtn = QtWidgets.QPushButton(parent=CustomerTab)
        self.addCustomerBtn.setObjectName("addCustomerBtn")
        self.horizontalLayout.addWidget(self.addCustomerBtn)
        self.updateCustomerBtn = QtWidgets.QPushButton(parent=CustomerTab)
        self.updateCustomerBtn.setObjectName("updateCustomerBtn")
        self.horizontalLayout.addWidget(self.updateCustomerBtn)
        self.deleteCustomerBtn = QtWidgets.QPushButton(parent=CustomerTab)
        self.deleteCustomerBtn.setObjectName("deleteCustomerBtn")
        self.horizontalLayout.addWidget(self.deleteCustomerBtn)
        self.refreshCustomerBtn = QtWidgets.QPushButton(parent=CustomerTab)
        self.refreshCustomerBtn.setObjectName("refreshCustomerBtn")
        self.horizontalLayout.addWidget(self.refreshCustomerBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(CustomerTab)
        QtCore.QMetaObject.connectSlotsByName(CustomerTab)

    def retranslateUi(self, CustomerTab):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox.setTitle(_translate("CustomerTab", "Customer Information"))
        self.label.setText(_translate("CustomerTab", "First Name:"))
        self.label_2.setText(_translate("CustomerTab", "Last Name:"))
        self.label_3.setText(_translate("CustomerTab", "Email:"))
        self.label_4.setText(_translate("CustomerTab", "Phone:"))
        item = self.customerTable.horizontalHeaderItem(0)
        item.setText(_translate("CustomerTab", "ID"))
        item = self.customerTable.horizontalHeaderItem(1)
        item.setText(_translate("CustomerTab", "First Name"))
        item = self.customerTable.horizontalHeaderItem(2)
        item.setText(_translate("CustomerTab", "Last Name"))
        item = self.customerTable.horizontalHeaderItem(3)
        item.setText(_translate("CustomerTab", "Email"))
        item = self.customerTable.horizontalHeaderItem(4)
        item.setText(_translate("CustomerTab", "Phone"))
        self.addCustomerBtn.setText(_translate("CustomerTab", "Add Customer"))
        self.updateCustomerBtn.setText(_translate("CustomerTab", "Update Customer"))
        self.deleteCustomerBtn.setText(_translate("CustomerTab", "Delete Customer"))
        self.refreshCustomerBtn.setText(_translate("CustomerTab", "Refresh"))
