

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PaymentTab(object):
    def setupUi(self, PaymentTab):
        PaymentTab.setObjectName("PaymentTab")
        PaymentTab.resize(1160, 740)
        self.verticalLayout = QtWidgets.QVBoxLayout(PaymentTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=PaymentTab)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.bookingCombo = QtWidgets.QComboBox(parent=self.groupBox)
        self.bookingCombo.setObjectName("bookingCombo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.bookingCombo)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.amountInput = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.amountInput.setMaximum(1000.0)
        self.amountInput.setObjectName("amountInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.amountInput)
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.paymentMethodCombo = QtWidgets.QComboBox(parent=self.groupBox)
        self.paymentMethodCombo.setObjectName("paymentMethodCombo")
        self.paymentMethodCombo.addItem("")
        self.paymentMethodCombo.addItem("")
        self.paymentMethodCombo.addItem("")
        self.paymentMethodCombo.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.paymentMethodCombo)
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.paymentStatusCombo = QtWidgets.QComboBox(parent=self.groupBox)
        self.paymentStatusCombo.setObjectName("paymentStatusCombo")
        self.paymentStatusCombo.addItem("")
        self.paymentStatusCombo.addItem("")
        self.paymentStatusCombo.addItem("")
        self.paymentStatusCombo.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.paymentStatusCombo)
        self.verticalLayout.addWidget(self.groupBox)
        self.paymentTable = QtWidgets.QTableWidget(parent=PaymentTab)
        self.paymentTable.setAlternatingRowColors(True)
        self.paymentTable.setObjectName("paymentTable")
        self.paymentTable.setColumnCount(7)
        self.paymentTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.paymentTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.paymentTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.paymentTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.paymentTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.paymentTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.paymentTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.paymentTable.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.paymentTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addPaymentBtn = QtWidgets.QPushButton(parent=PaymentTab)
        self.addPaymentBtn.setObjectName("addPaymentBtn")
        self.horizontalLayout.addWidget(self.addPaymentBtn)
        self.updatePaymentBtn = QtWidgets.QPushButton(parent=PaymentTab)
        self.updatePaymentBtn.setObjectName("updatePaymentBtn")
        self.horizontalLayout.addWidget(self.updatePaymentBtn)
        self.deletePaymentBtn = QtWidgets.QPushButton(parent=PaymentTab)
        self.deletePaymentBtn.setObjectName("deletePaymentBtn")
        self.horizontalLayout.addWidget(self.deletePaymentBtn)
        self.refreshPaymentBtn = QtWidgets.QPushButton(parent=PaymentTab)
        self.refreshPaymentBtn.setObjectName("refreshPaymentBtn")
        self.horizontalLayout.addWidget(self.refreshPaymentBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(PaymentTab)
        QtCore.QMetaObject.connectSlotsByName(PaymentTab)

    def retranslateUi(self, PaymentTab):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox.setTitle(_translate("PaymentTab", "Payment Information"))
        self.label.setText(_translate("PaymentTab", "Booking:"))
        self.label_2.setText(_translate("PaymentTab", "Amount:"))
        self.amountInput.setPrefix(_translate("PaymentTab", "$ "))
        self.label_3.setText(_translate("PaymentTab", "Payment Method:"))
        self.paymentMethodCombo.setItemText(0, _translate("PaymentTab", "Credit Card"))
        self.paymentMethodCombo.setItemText(1, _translate("PaymentTab", "Debit Card"))
        self.paymentMethodCombo.setItemText(2, _translate("PaymentTab", "Cash"))
        self.paymentMethodCombo.setItemText(3, _translate("PaymentTab", "Mobile Payment"))
        self.label_4.setText(_translate("PaymentTab", "Payment Status:"))
        self.paymentStatusCombo.setItemText(0, _translate("PaymentTab", "Completed"))
        self.paymentStatusCombo.setItemText(1, _translate("PaymentTab", "Pending"))
        self.paymentStatusCombo.setItemText(2, _translate("PaymentTab", "Failed"))
        self.paymentStatusCombo.setItemText(3, _translate("PaymentTab", "Refunded"))
        item = self.paymentTable.horizontalHeaderItem(0)
        item.setText(_translate("PaymentTab", "Payment ID"))
        item = self.paymentTable.horizontalHeaderItem(1)
        item.setText(_translate("PaymentTab", "Customer"))
        item = self.paymentTable.horizontalHeaderItem(2)
        item.setText(_translate("PaymentTab", "Movie"))
        item = self.paymentTable.horizontalHeaderItem(3)
        item.setText(_translate("PaymentTab", "Amount"))
        item = self.paymentTable.horizontalHeaderItem(4)
        item.setText(_translate("PaymentTab", "Payment Method"))
        item = self.paymentTable.horizontalHeaderItem(5)
        item.setText(_translate("PaymentTab", "Status"))
        item = self.paymentTable.horizontalHeaderItem(6)
        item.setText(_translate("PaymentTab", "Payment Date"))
        self.addPaymentBtn.setText(_translate("PaymentTab", "Add Payment"))
        self.updatePaymentBtn.setText(_translate("PaymentTab", "Update Payment"))
        self.deletePaymentBtn.setText(_translate("PaymentTab", "Delete Payment"))
        self.refreshPaymentBtn.setText(_translate("PaymentTab", "Refresh"))
